#!/usr/bin/env python
import os

from lib.python.the_bloodhound_cli import BloodhoundCLI

def main():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    BloodhoundCLI.bloodhound_cli()


if __name__ == '__main__':
    main()